/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-13 16:31:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class likedPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1699882916934L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1699885205184L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>New 2023 Jeep Compass Latitude Lux</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style2.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Electric Car Shop</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">Electric Car Shop</a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"loginPage.jsp\" class=\"btn btn-outline-light ml-2\" id=\"loginButton\">Login</a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"filterPage.jsp\" class=\"btn btn-outline-light ml-2\" id=\"filterButton\">Filter</a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"likedPage.jsp\" class=\"btn btn-outline-light ml-2\" id=\"likedButton\">\r\n");
      out.write("            <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> Liked\r\n");
      out.write("        </a>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- Car title -->\r\n");
      out.write("        <div class=\"vehicle-header\">\r\n");
      out.write("            <h1>New 2023 Jeep Compass Latitude Lux</h1>\r\n");
      out.write("            <!-- Car details like mileage etc. -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Image gallery -->\r\n");
      out.write("        <div class=\"row vehicle-images\">\r\n");
      out.write("        <div class=\"col-md-8\">\r\n");
      out.write("            <!-- Main image -->\r\n");
      out.write("            <img src=\"https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800*392/v1617545827/direct/GREAT-WALL_aqj7cc.jpg\" alt=\"Primary View of Car\" id=\"mainCarImage\" class=\"img-fluid\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <!-- Thumbnails -->\r\n");
      out.write("            <!-- Repeat this block for each thumbnail you have -->\r\n");
      out.write("            <div class=\"thumbnail\" onclick=\"setMainImage(this)\">\r\n");
      out.write("                <img src=\"https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800*392/v1617545827/direct/GREAT-WALL_aqj7cc.jpg\" alt=\"Thumbnail View of Car\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"thumbnail\" onclick=\"setMainImage(this)\">\r\n");
      out.write("                <img src=\"https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800*392/v1617545827/direct/GREAT-WALL_aqj7cc.jpg\" alt=\"Thumbnail View of Car\">\r\n");
      out.write("            </div><div class=\"thumbnail\" onclick=\"setMainImage(this)\">\r\n");
      out.write("                <img src=\"https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800*392/v1617545827/direct/GREAT-WALL_aqj7cc.jpg\" alt=\"Thumbnail View of Car\">\r\n");
      out.write("            </div><div class=\"thumbnail\" onclick=\"setMainImage(this)\">\r\n");
      out.write("                <img src=\"https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800*392/v1617545827/direct/GREAT-WALL_aqj7cc.jpg\" alt=\"Thumbnail View of Car\">\r\n");
      out.write("            </div><div class=\"thumbnail\" onclick=\"setMainImage(this)\">\r\n");
      out.write("                <img src=\"https://res.cloudinary.com/globes/image/upload/t_desktop_article_content_header_800*392/v1617545827/direct/GREAT-WALL_aqj7cc.jpg\" alt=\"Thumbnail View of Car\">\r\n");
      out.write("            </div><div class=\"thumbnail\" onclick=\"setMainImage(this)\">\r\n");
      out.write("                <img src=\"https://paultan.org/image/2022/09/Huawei-AITO-Wenjie-M5-EV-China-1.jpg\" alt=\"Thumbnail View of Car\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Add more thumbnails as needed -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Vehicle overview -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("                <div class=\"overview-item\">\r\n");
      out.write("                    <h2>Vehicle Overview</h2>\r\n");
      out.write("                    <!-- Overview content -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"price-section\">\r\n");
      out.write("                    <h3>Cash Price</h3>\r\n");
      out.write("                    <p>$38,795</p>\r\n");
      out.write("                    <!-- Finance content -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("  <a href=\"link_car.jsp\" class=\"card\">\r\n");
      out.write("    <img src=\"https://paultan.org/image/2022/09/Huawei-AITO-Wenjie-M5-EV-China-1.jpg\" alt=\"Huawei AITO M5 EV\">\r\n");
      out.write("    <div class=\"details\">\r\n");
      out.write("      <h2>Huawei AITO M5 EV</h2>\r\n");
      out.write("      <p>Price: $35,000</p>\r\n");
      out.write("      <p>Mileage: 10,000 miles</p>\r\n");
      out.write("      <p>Location: Incheon, South Korea</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </a>\r\n");
      out.write("  <a href=\"link-to-car-page.html\" class=\"card\">\r\n");
      out.write("    <img src=\"https://www.cartoq.com/wp-content/uploads/2022/01/huawei-aito-m5-electric-car-fb.jpg\" alt=\"Huawei AITO M5 EV\">\r\n");
      out.write("    <div class=\"details\">\r\n");
      out.write("      <h2>Huawei AITO M5 EV</h2>\r\n");
      out.write("      <p>Price: $35,000</p>\r\n");
      out.write("      <p>Mileage: 10,000 miles</p>\r\n");
      out.write("      <p>Location: Incheon, South Korea</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </a><a href=\"link-to-car-page.html\" class=\"card\">\r\n");
      out.write("    <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxWbI545x5tueyWRU16C-3dh1iCfhv1srzdRDUSX-XBqNB1s6JjAKHqfvQxc5OxhJs2h0&usqp=CAU\">\r\n");
      out.write("    <div class=\"details\">\r\n");
      out.write("      <h2>Huawei AITO M5 EV</h2>\r\n");
      out.write("      <p>Price: $35,000</p>\r\n");
      out.write("      <p>Mileage: 10,000 miles</p>\r\n");
      out.write("      <p>Location: Incheon, South Korea</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </a><a href=\"link-to-car-page.html\" class=\"card\">\r\n");
      out.write("    <img src=\"https://paultan.org/image/2022/09/Huawei-AITO-Wenjie-M5-EV-China-1.jpg\" alt=\"Huawei AITO M5 EV\">\r\n");
      out.write("    <div class=\"details\">\r\n");
      out.write("      <h2>Huawei AITO M5 EV</h2>\r\n");
      out.write("      <p>Price: $35,000</p>\r\n");
      out.write("      <p>Mileage: 10,000 miles</p>\r\n");
      out.write("      <p>Location: Incheon, South Korea</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS and dependencies -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    // JavaScript function to change the main image\r\n");
      out.write("    function setMainImage(thumbnailElement) {\r\n");
      out.write("        // Find the main image by its ID\r\n");
      out.write("        var mainImage = document.getElementById('mainCarImage');\r\n");
      out.write("        // Change its 'src' to the 'src' of the thumbnail clicked\r\n");
      out.write("        mainImage.src = thumbnailElement.children[0].src;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write(" ");
      out.write("<footer class=\"bg-dark text-white mt-4\">\r\n");
      out.write("    <div class=\"container-fluid py-3\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center\">\r\n");
      out.write("                &copy; 2023 Electric Car Shop. All rights reserved.\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    // JavaScript for Button functionalities\r\n");
      out.write("    // Add actual implementations or remove these if not needed\r\n");
      out.write("    document.getElementById('loginButton').addEventListener('click', function() {\r\n");
      out.write("        // Implement login functionality here\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('filterButton').addEventListener('click', function() {\r\n");
      out.write("        // Implement filter functionality here\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('likedButton').addEventListener('click', function() {\r\n");
      out.write("        // Implement liked functionality here\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
