/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-14 14:11:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainPpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1699882916934L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1699885205184L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Electric Car Shop</title>\r\n");
      out.write("   <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Electric Car Shop</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">Electric Car Shop</a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"loginPage.jsp\" class=\"btn btn-outline-light ml-2\" id=\"loginButton\">Login</a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"filterPage.jsp\" class=\"btn btn-outline-light ml-2\" id=\"filterButton\">Filter</a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"likedPage.jsp\" class=\"btn btn-outline-light ml-2\" id=\"likedButton\">\r\n");
      out.write("            <i class=\"fa fa-heart\" aria-hidden=\"true\"></i> Liked\r\n");
      out.write("        </a>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!-- Carousel -->\r\n");
      out.write("  \r\n");
      out.write("    <div id=\"carouselExampleCaptions\" class=\"carousel slide\">\r\n");
      out.write("  <div class=\"carousel-indicators\">\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"3\" aria-label=\"Slide 4\"></button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("    <div class=\"carousel-item active\">\r\n");
      out.write("      <img src=\"https://carnewschina.com/wp-content/uploads/2022/02/008pSCi0ly1gyr4y68fuyj318z0u0n331-1.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("        <h5>First slide label</h5>\r\n");
      out.write("        <p>Some representative placeholder content for the first slide.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"https://i0.wp.com/technode.com/wp-content/uploads/2022/03/AITO3.jpeg?fit=1200%2C809&ssl=1\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("        <h5>Second slide label</h5>\r\n");
      out.write("        <p>Some representative placeholder content for the second slide.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"https://www.cartoq.com/wp-content/uploads/2022/01/huawei-aito-m5-electric-car-fb.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("        <h5>Third slide label</h5>\r\n");
      out.write("        <p>Some representative placeholder content for the third slide.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"https://www.carscoops.com/wp-content/uploads/2022/03/Aito-M5-main.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("        <h5>forth slide label</h5>\r\n");
      out.write("        <p>Some representative placeholder content for the third slide.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write(" <div id=\"background3D\"></div>\r\n");
      out.write("    <!-- Search Bar -->\r\n");
      out.write("    <div class=\"row mt-4\">\r\n");
      out.write("        <div class=\"col-md-8 offset-md-2\">\r\n");
      out.write("            <form class=\"form-inline justify-content-center\">\r\n");
      out.write("                <input class=\"form-control mr-sm-2 w-50\" type=\"search\" placeholder=\"Search make, model, or type\" aria-label=\"Search\">\r\n");
      out.write("                <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container my-5\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6 my-auto\">\r\n");
      out.write("            <h2>Finally, it's Easy.</h2>\r\n");
      out.write("            <p>Bring the dealership to your doorstep.</p>\r\n");
      out.write("            <p>Find your perfect match from the comfort of home and shop millions of new and used cars based on your budget.</p>\r\n");
      out.write("            <a href=\"cars.jsp\" class=\"btn btn-primary\">Find Your Next Car</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("              <div class=\"custom-background\"></div>\r\n");
      out.write("               <img src=\"https://t3.ftcdn.net/jpg/05/30/63/92/360_F_530639220_h6dCEX1xdMvyKfGpQZH9fIXSVnZD3ZPS.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Section Container -->\r\n");
      out.write("<div class=\"why-section\">\r\n");
      out.write("  <!-- Single Feature Column -->\r\n");
      out.write("  <div class=\"feature\">\r\n");
      out.write("    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1024px-Flat_tick_icon.svg.png\" alt=\"Icon 1\">\r\n");
      out.write("    <h3>Transparent pricing</h3>\r\n");
      out.write("    <p>No surprises here. See how much you'll pay on cars you like.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Single Feature Column -->\r\n");
      out.write("  <div class=\"feature\">\r\n");
      out.write("    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1024px-Flat_tick_icon.svg.png\" alt=\"Icon 2\">\r\n");
      out.write("    <h3>Minutes, not hours</h3>\r\n");
      out.write("    <p>Time-saving tools to help you find the right car in a snap.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Single Feature Column -->\r\n");
      out.write("  <div class=\"feature\">\r\n");
      out.write("    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1024px-Flat_tick_icon.svg.png\" alt=\"Icon 3\">\r\n");
      out.write("    <h3>Shop your way</h3>\r\n");
      out.write("    <p>Your own pace, your own space. Shop online where and when it's convenient for you.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Button -->\r\n");
      out.write("  <button class=\"browse-button\">Browse local inventory</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"dual-promo-container\">\r\n");
      out.write("  <div class=\"promo-block sell-trade\">\r\n");
      out.write("    <h2>Sell and trade</h2>\r\n");
      out.write("    <p>Answer a few questions and get an instant offer.</p>\r\n");
      out.write("    <a href=\"#\" class=\"btn\">Learn more</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"promo-block military-savings\">\r\n");
      out.write("    <h2>Military savings</h2>\r\n");
      out.write("    <p>Find savings and incentives tailored for active duty military, veterans, and family.</p>\r\n");
      out.write("    <a href=\"#\" class=\"btn\">Learn more</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container my-5\">\r\n");
      out.write("    <h3>Shop Vehicles by Style</h3>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-4 col-md-3 text-center\">\r\n");
      out.write("            <img src=\"https://png.pngtree.com/png-clipart/20190618/original/pngtree-electric-car-new-energy-cute-ui-design-png-image_3938220.jpg\" alt=\"Truck\" class=\"img-fluid\">\r\n");
      out.write("            <h4>Sedan</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-4 col-md-3 text-center\">\r\n");
      out.write("            <img src=\"https://png.pngtree.com/png-clipart/20190618/original/pngtree-electric-car-new-energy-cute-ui-design-png-image_3938220.jpg\" alt=\"Truck\" class=\"img-fluid\">\r\n");
      out.write("            <h4>Truck</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-4 col-md-3 text-center\">\r\n");
      out.write("            <img src=\"https://png.pngtree.com/png-clipart/20190618/original/pngtree-electric-car-new-energy-cute-ui-design-png-image_3938220.jpg\" alt=\"Truck\" class=\"img-fluid\">\r\n");
      out.write("            <h4>Truck</h4>\r\n");
      out.write("        </div><div class=\"col-sm-4 col-md-3 text-center\">\r\n");
      out.write("            <img src=\"https://png.pngtree.com/png-clipart/20190618/original/pngtree-electric-car-new-energy-cute-ui-design-png-image_3938220.jpg\" alt=\"Truck\" class=\"img-fluid\">\r\n");
      out.write("            <h4>Truck</h4>\r\n");
      out.write("        </div><div class=\"col-sm-4 col-md-3 text-center\">\r\n");
      out.write("            <img src=\"https://png.pngtree.com/png-clipart/20190618/original/pngtree-electric-car-new-energy-cute-ui-design-png-image_3938220.jpg\" alt=\"Truck\" class=\"img-fluid\">\r\n");
      out.write("            <h4>Truck</h4>\r\n");
      out.write("        </div><div class=\"col-sm-4 col-md-3 text-center\">\r\n");
      out.write("            <img src=\"https://png.pngtree.com/png-clipart/20190618/original/pngtree-electric-car-new-energy-cute-ui-design-png-image_3938220.jpg\" alt=\"Truck\" class=\"img-fluid\">\r\n");
      out.write("            <h4>Truck</h4>\r\n");
      out.write("        </div><div class=\"col-sm-4 col-md-3 text-center\">\r\n");
      out.write("            <img src=\"https://png.pngtree.com/png-clipart/20190618/original/pngtree-electric-car-new-energy-cute-ui-design-png-image_3938220.jpg\" alt=\"Truck\" class=\"img-fluid\">\r\n");
      out.write("            <h4>Truck</h4>\r\n");
      out.write("        </div><div class=\"col-sm-4 col-md-3 text-center\">\r\n");
      out.write("            <img src=\"https://png.pngtree.com/png-clipart/20190618/original/pngtree-electric-car-new-energy-cute-ui-design-png-image_3938220.jpg\" alt=\"Truck\" class=\"img-fluid\">\r\n");
      out.write("            <h4>Truck</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<footer class=\"bg-dark text-white mt-4\">\r\n");
      out.write("    <div class=\"container-fluid py-3\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center\">\r\n");
      out.write("                &copy; 2023 Electric Car Shop. All rights reserved.\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    // JavaScript for Button functionalities\r\n");
      out.write("    // Add actual implementations or remove these if not needed\r\n");
      out.write("    document.getElementById('loginButton').addEventListener('click', function() {\r\n");
      out.write("        // Implement login functionality here\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('filterButton').addEventListener('click', function() {\r\n");
      out.write("        // Implement filter functionality here\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('likedButton').addEventListener('click', function() {\r\n");
      out.write("        // Implement liked functionality here\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
